"""Observe (observe.inc) integration env-var names and defaults."""

OBSERVE_CUSTOMER_ID_ENV = "OBSERVE_CUSTOMER_ID"
OBSERVE_API_TOKEN_ENV = "OBSERVE_API_TOKEN"
OBSERVE_BASE_URL_ENV = "OBSERVE_BASE_URL"

__all__ = ["OBSERVE_API_TOKEN_ENV", "OBSERVE_BASE_URL_ENV", "OBSERVE_CUSTOMER_ID_ENV"]
